### ISSUE TITLE
storage権限ないのでデプロイ失敗する

### ISSUE THREAD

**Issue by utamori** [utamori/gin-gorm-run-sql#3]
> denied: Token exchange failed for project '***'. Caller does not have permission 'storage.buckets.create'. To configure permissions, follow instructions at: https://cloud.google.com/container-registry/docs/access-control

イメージを保存するのはGCSなんだしそらそうだ

SAに権限追加

**Comment by utamori** [comment]
`storage.buckets.create`はオーナーと編集者しか持たない
SAごときにそんなロール持たせるのはどうかと思うが、閲覧者から編集者に昇格

本当はカスタムロール作成する必要がある。

**Comment by uta-mori** [comment]
#4

**Comment by utamori** [comment]
#4
